"""Generate the native vector subset; development-only dependency: fonttools 4.64.0.

Run with PYTHONPATH pointing at an optional local fonttools installation.
SVGs and LICENSE are pinned, retained verbatim, and never fetched by Veyra.
"""
from pathlib import Path
import hashlib
import json
import urllib.request
import xml.etree.ElementTree as ET
from fontTools.svgLib.path import parse_path
from fontTools.pens.recordingPen import RecordingPen

ROOT = Path(__file__).resolve().parents[1]
REVISION = "a537cb6eb323b885f4c60baf3cec1a995982d167"
ICONS = dict(Play="play", Pause="pause", Stop="square", Volume="volume-2",
             Muted="volume-x", Fullscreen="maximize", Video="folder-open",
             Capture="monitor", Image="image", Subtitle="captions",
             Minimize="minus", Maximize="square", Close="x", Back="chevron-left",
             Settings="sliders-horizontal", Recent="clock", Enhance="sparkles",
             Upscale="scan", PanelOpen="panel-right-open", PanelClose="panel-right-close",
             Check="check", Chevron="chevron-down", Load="file-plus", Type="type",
             ScreenCapture="app-window", Reset="rotate-ccw", Lock="lock-keyhole")
DEST = ROOT / "assets/icons/lucide"
DEST.mkdir(parents=True, exist_ok=True)
manifest = {"repository": "https://github.com/lucide-icons/lucide", "revision": REVISION,
            "generator": "fonttools 4.64.0; SVG paths converted to GDI+ cubic paths", "sha256": {}}
for name in ["LICENSE"] + [f"icons/{n}.svg" for n in sorted(set(ICONS.values()))]:
    file = DEST / name.rsplit("/", 1)[-1]
    if not file.exists():
        print(f"Fetching {name}", flush=True)
        file.write_bytes(urllib.request.urlopen(f"https://raw.githubusercontent.com/lucide-icons/lucide/{REVISION}/{name}").read())
    manifest["sha256"][file.name] = hashlib.sha256(file.read_bytes()).hexdigest()

def paths(element):
    a = element.attrib
    tag = element.tag.split("}")[-1]
    if tag == "path": return a["d"]
    if tag == "line": return f'M{a["x1"]} {a["y1"]}L{a["x2"]} {a["y2"]}'
    if tag in ("polyline", "polygon"): return "M" + a["points"] + ("Z" if tag == "polygon" else "")
    if tag == "circle":
        x, y, r = [float(a[k]) for k in ("cx", "cy", "r")]
        return f"M{x-r} {y}a{r} {r} 0 1 0 {2*r} 0a{r} {r} 0 1 0 {-2*r} 0Z"
    if tag == "rect":
        x,y,w,h = [float(a.get(k,0)) for k in ("x","y","width","height")]
        r = min(float(a.get("rx",0)),w/2,h/2)
        if not r: return f"M{x} {y}h{w}v{h}h{-w}Z"
        return f"M{x+r} {y}h{w-2*r}a{r} {r} 0 0 1 {r} {r}v{h-2*r}a{r} {r} 0 0 1 {-r} {r}h{2*r-w}a{r} {r} 0 0 1 {-r} {-r}v{2*r-h}a{r} {r} 0 0 1 {r} {-r}Z"
    raise ValueError(tag)

def number(v): return f"{float(v):.7f}f"
def point(p): return ",".join(map(number,p))
output = ["// Generated by scripts/generate-lucide-icons.py. Do not hand edit.",
          "// Lucide ISC + Feather MIT; full notices: assets/icons/lucide/LICENSE.",
          "#pragma once", '#include "GlassMaterial.h"', "namespace veyra::ui {",
          "enum class Icon { None," + ",".join(ICONS) + " };",
          "inline void drawIcon(HDC dc,Icon icon,float x,float y,float size,COLORREF c){",
          "using namespace Gdiplus; AlphaGraphics drawing(dc);auto& g=drawing.get();",
          "g.SetSmoothingMode(SmoothingModeAntiAlias);g.TranslateTransform(x-size/2,y-size/2);g.ScaleTransform(size/24,size/24);",
          "Pen pen(Color(255,GetRValue(c),GetGValue(c),GetBValue(c)),1.8f);pen.SetStartCap(LineCapRound);pen.SetEndCap(LineCapRound);pen.SetLineJoin(LineJoinRound);GraphicsPath p;switch(icon){"]
for key,name in ICONS.items():
    output.append(f"case Icon::{key}: // {name}.svg")
    for element in ET.parse(DEST / f"{name}.svg").getroot():
        pen = RecordingPen()
        parse_path(paths(element),pen)
        current = None
        for op,args in pen.value:
            if op == "moveTo":
                output.append("p.StartFigure();")
                current = args[0]
            elif op == "lineTo":
                output.append(f"p.AddLine({point(current)},{point(args[0])});")
                current = args[0]
            elif op == "curveTo":
                assert len(args)==3
                output.append("p.AddBezier(" + ",".join(point(v) for v in (current, *args)) + ");")
                current = args[-1]
            elif op == "closePath": output.append("p.CloseFigure();")
            elif op != "endPath": raise ValueError(op)
    output.append("break;")
output += ["default: return;}g.DrawPath(&pen,&p);", "}", "}", ""]
(ROOT / "apps/veyra/ui/LucideIcons.h").write_text("\n".join(output),encoding="utf-8")
(DEST / "manifest.json").write_text(json.dumps(manifest,indent=2)+"\n",encoding="utf-8")
print(f"Generated {len(ICONS)} native icons from {REVISION}")
